### ISSUE TITLE
WPF Trace Level - Crashes VS

### ISSUE THREAD

**Issue by Symbai** [spadapet/xaml-binding-tool#14]
Binding tool 1.16 and VS 16.3.9 debugging a WPF .NET Core 3 application. Sooner or later changing the trace level or clicking on the "..." button crashes VS. It seems to happen more earlier when clicking the feedback button once.

Demo, speed up first part when trying to repro:
![Untitled Project](https://user-images.githubusercontent.com/14368203/68908301-c4403680-0742-11ea-99e6-57bc54d79883.gif)

**Comment by spadapet** [comment]
Thanks! Looks like a problem specifically with "Activity" being selected when showing the options dialog. I attached VS to VS and got this callstack:

![image](https://user-images.githubusercontent.com/2523431/68971824-3d6d7700-079f-11ea-9cb7-9fa5e75b51cc.png)

I'll have to see if Activity really belongs in the list, or maybe that value is supposed to write a special value to the registry.

**Comment by spadapet** [comment]
Fixed in VSIX version 1.18
Commit 91c82f418babed780823bb5ae8b140bfd3bea183

**Comment by spadapet** [comment]
By the way, VS stores "ActivityTracing" in the registry when you choose "Activity". I didn't realize that, all the other options store the display string as the value in the registry. (a bad value shouldn't crash VS though, but it does)
