### ISSUE TITLE
A chance to provide more useful errors?

### ISSUE THREAD

**Issue by Symbai** [spadapet/xaml-binding-tool#15]
Sometimes this tool is showing errors which are impossible to find out the reason for it. They don't contain any property name, nor control name, nor any source code line number. This is typical for VS but I had hoped this extension would / could provide more information. Any chance?

> Severity	Code	Count	Data Context Type	Binding Path	Target	Description
> Error	4	1				Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Window', AncestorLevel='1''. BindingExpression:Path=DataContext; DataItem=null; target element is 'Grid' (Name=''); target property is 'DataContext' (type 'Object')

_I would love if VS would give us the possibility to break and debug on exception like in normal source code...._

**Comment by spadapet** [comment]
@Symbai With this extension, it can't get any more  information than what's in the debug output window. WPF doesn't expose any way to get source code line numbers for a binding failure. Also, it doesn't have a way for the debugger break on any binding failure.

For that example error code 4 you pasted, all I can do is add a regex to extract out bits of information to make it easier to read in the columns of this extension's tool window. That will happen, like extracting the binding path of "DataContext" and target of "Grid.DataContext". That makes the error easier to read, but doesn't provide more info than you already had.

However... the goal is to take the ideas in this extension and become a built-in feature in Visual Studio. And from there we can start updating the platforms (WPF, etc) to allow what you want, like source information or better ways to debug failures.

**Comment by Symbai** [comment]
That would be great, thank you!
