### ISSUE TITLE
Support hot reload

### ISSUE THREAD

**Issue by linhofen** [spadapet/xaml-binding-tool#22]
When editing a xaml page, the application is running and you correct a binding error, it would be nice to have a reload of the binding failures related to the edited page.

EDIT: It reloads when you add a failure, but not when you remove one.

**Comment by spadapet** [comment]
By looking at the debug output for binding failures, there's no way to know when a {Binding} succeeds after it has failed. This extension is like the output window where it logs the events that have happened.

Here's an idea: Would it be useful if you were able to delete binding errors from the list manually?  What you could do is delete some errors that you're about to work on, make the edit, and the errors would show up again (or not) when hot reload updates the binding that you've typed.

**Comment by linhofen** [comment]
Ok, I understand! For me using "Delete all" or manually deleting a failure doesn't make a big difference. If other people request it or you want to implement it, no problem. For my personal workflow though, it is not a necessity.

**Comment by spadapet** [comment]
Sounds good, thanks for the feedback!
