### ISSUE TITLE
Disable auto popup and capture focus

### ISSUE THREAD

**Issue by Flithor** [spadapet/xaml-binding-tool#32]
When I modify the xmal for hot-fix in runtime, it interrupts my input very frequently - it snatch the focus.

**Comment by spadapet** [comment]
Hmm, the pane shouldn't auto pop up by default. But there is an option that might be causing problems. Look in Tools | Options | Debugger | XAML Binding Failures:

![image](https://user-images.githubusercontent.com/2523431/90178274-8408f580-dd60-11ea-9eb7-fcee57951462.png)

Do you have "Show tool window pane" set to True?

**Comment by DavidHollman** [comment]
> Do you have "Show tool window pane" set to True?

I had the same problem, and setting this to False fixed it for me. VS2019 Version 16.8.4.

Thanks

**Comment by spadapet** [comment]
Thanks for the comment, I'll close this then. These options were added for fun in this "experimental" extension, and aren't part of the XAML Binding Failures tool window built into VS2019 16.8.
