### ISSUE TITLE
Not seeing any items in the XAML Binding Failures (experimental) tab

### ISSUE THREAD

**Issue by PeterJarrettUK** [spadapet/xaml-binding-tool#33]
I've just installed the VSIX and the docked window is now visible, but I'm not seeing any items appearing in the window.

In my immediate window, I'm still seeing binding errors in there such as:

`System.Windows.Data Error: 40 : BindingExpression path error: 'IsExpanded' property not found on 'object' ''ViewModel' (HashCode=46080827)'. BindingExpression:Path=IsExpanded; DataItem='ViewModel' (HashCode=46080827); target element is 'TreeViewItem' (Name='AllItemsTreeViewItem'); target property is 'IsExpanded' (type 'Boolean')`

I'm running VS2019 16.6.3 and the application is a WPF Application targeting .NET Framework 4.6.1

Is it possible i've got something disabled in my VS settings that would be preventing xbt from picking up the errors?

**Comment by spadapet** [comment]
@Mostlypyjamas You say "immediate window", so are you routing all output window text to the immediate window? This extension only looks at the output window (didn't even think about immediate window)

**Comment by spadapet** [comment]
(sorry for such a delayed response, I missed some issues while I was on paternity leave)

**Comment by spadapet** [comment]
The released feature in Visual Studio 2019 16.9 supports the immediate window. Check out the feature there (you can uninstall this extension)
