### ISSUE TITLE
Future of this extension after the release of the new XAML Binding Failures window in VS 2019 16.7

### ISSUE THREAD

**Issue by Otiel** [spadapet/xaml-binding-tool#34]
In a recent [blog post](https://devblogs.microsoft.com/visualstudio/improvements-to-xaml-tooling-in-visual-studio-2019-version-16-7-preview-1/) (May 20th, 2020), Microsoft has unveiled new capabilities in VS 2019 regarding the debugging of XAML binding failures, notably a new window that looks very much like the one offered by XAML Binding Debug Output:

>**New XAML Binding Failures** window that brings binding failure details previously only available in the Output window and makes them easy to review in the new dedicated window. The window adds features such as sorting, searching and grouping of similar errors. This experience works for WPF, UWP and Xamarin.Forms projects.
>
>![image](https://user-images.githubusercontent.com/3851902/90133024-0ef0ec80-dd6f-11ea-8141-2119f63ef202.png)

Since this extension is only compatible with VS 2019, will it be made obsolete once the new VS window comes out of preview?

**Comment by chucker** [comment]
The built-in feature is just a newer version of this (experimental) extension, I believe.

**Comment by jzabroski** [comment]
Yeah, @spadapet works at Microsoft, so it would be no surprise to me if Microsoft decided to effectively commercialize his hobby.

**Comment by spadapet** [comment]
Yes, I was able to rewrite this extension as a real feature in Visual Studio 16.7 (starting as a preview feature). The extension still has some extra things that probably won't make it into the product though (like the dropdown that changes WPF output, and the Tools|Options page that lets you play a sound for every binding failure)

But don't expect anything new in this extension, the feature in VS is going to get all the new features (like double clicking to go to the failed {Binding} in markup). The in-app toolbar button that shows the binding failure count is already something better in the product that I couldn't possibly add as an extension.

**Comment by spadapet** [comment]
Check out the feature in Visual Studio 16.9. It's able to do more, such as deleting rows, and double-click to go to the failure for WPF .NET 5 and Xamarin 5

**Comment by Otiel** [comment]
Thanks for the heads-up!
