### ISSUE TITLE
Play a sound 🔊 on new errors

### ISSUE THREAD

**Issue by omariom** [spadapet/xaml-binding-tool#7]
Even Console.Beep would do.

Ideally allow to choose among [SystemSounds](https://docs.microsoft.com/en-us/dotnet/api/system.media.systemsounds?view=netframework-4.8)

**Comment by spadapet** [comment]
Probably not going to do this one for a long time, or it might become a Won't Fix :)
Or... make an extensibility point where someone could add a sound in another extension.

**Comment by spadapet** [comment]
Actually it wouldn’t be hard to add a Tools|Options page for this extension and then have the sound option in there, off by default.

**Comment by spadapet** [comment]
This was mostly for fun and a way to learn how to add a Tools|Options dialog:

![image](https://user-images.githubusercontent.com/2523431/68496108-712c2800-0206-11ea-9f3b-b29605a888ab.png)

Commit eda7eee6a925d813ca1ee6ea14ca821714b8422e

**Comment by spadapet** [comment]
In version 1.16 of the extension (just uploaded to the marketplace)
