### ISSUE TITLE
Xamarin.Forms XAML Support :)

### ISSUE THREAD

**Issue by jamesmontemagno** [spadapet/xaml-binding-tool#8]
How do we help make it happen :)

**Comment by spadapet** [comment]
Right now I'm going to focus on making the regex to parse WPF binding errors (there are a lot). That's all in XamlBinding/Parser/WpfOutputParser.cs.

For Xamarin, it should be a matter of having another implementation of IOutputParser just like WpfOutputParser.cs. Then the tool window will decide which parser to use based on the project type.

**Comment by LyalinDotCom** [comment]
@jamesmontemagno we're also actively working with the Xamarin.Forms team on getting this done so it will happen :)

**Comment by spadapet** [comment]
Version 1.24 now parses Xamarin binding errors from the debug output. The error messages aren't as rich as WPF/UWP, so all the columns aren't filled out, but at least they show up.
Like @LyalinDotCom said, we're working with the Xamarin.Forms team to make it better.

**Comment by EmilAlipiev** [comment]
is it now integrated into VS 2019 pre? i saw other day the presentation similar to this

**Comment by spadapet** [comment]
@EmilAlipiev Yes it is. It's in VS 2019 preview builds for version 16.8 (Tools | Options | Environment | Preview Features)

**Comment by LyalinDotCom** [comment]
@EmilAlipiev As Peter said this is still in preview so if you don't have a preview installed you can't enable it and the extension here is now out-of-date relative to the in-product work we're doing. We are hoping to launch this officially soon, so preview won't be required in the future. If you try this in Preview and have any feedback let us know!
